{
 "title": "Default",
 "time": { "from": "2024-03-10T22:26:16.000Z", "to": "2024-03-10T22:30:10.446Z" },
 "panels": [
  { "title": "ASP.NET Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "active" }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code, http_request_method, http_route) (rate(http_server_request_duration_count[$__rate_interval]))",
     "legendFormat": "{{http_response_status_code}} {{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Queued Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    { "expr": "kestrel_queued_requests", "legendFormat": "active" }
   ]
  },
  {
   "title": "Response Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (http_server_request_duration_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "targets": [
    { "expr": "kestrel_active_connections", "legendFormat": "active" }
   ]
  },
  {
   "title": "Queued Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "targets": [
    { "expr": "kestrel_queued_connections", "legendFormat": "active" }
   ]
  },
  {
   "title": "Rejected Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "targets": [
    { "expr": "kestrel_rejected_connections", "legendFormat": "active" }
   ]
  },
  {
   "title": "Response Time Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (http_client_request_duration_bucket))",
     "legendFormat": "90p"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (http_client_request_duration_bucket))",
     "legendFormat": "99p"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (rate(process_cpu_time[$__rate_interval]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(process_runtime_dotnet_gc_committed_memory_size)",
     "legendFormat": "committed bytes"
    }
   ]
  },
  {
   "title": "ThreadPool Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(process_runtime_dotnet_thread_pool_queue_length)",
     "legendFormat": "length"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_runtime_dotnet_exceptions_count[$__rate_interval]))",
     "legendFormat": "exceptions"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "max(process_threads)", "legendFormat": "threads" }
   ]
  },
  {
   "title": "ThreadPool Completed Items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(process_runtime_dotnet_thread_pool_completed_items_count[$__rate_interval]))",
     "legendFormat": "items"
    }
   ]
  },
  {
   "title": "Lock Contention",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(process_runtime_dotnet_monitor_lock_contention_count[$__rate_interval]))",
     "legendFormat": "contention"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by (generation) (60 * rate(process_runtime_dotnet_gc_collections_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(process_runtime_dotnet_gc_allocations_size[$__rate_interval]))",
     "legendFormat": "allocation"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(process_runtime_dotnet_gc_duration[$__rate_interval]))",
     "legendFormat": "duration"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Command Bytes Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(db_client_commands_bytes_read[$__rate_interval]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Command Bytes Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(db_client_commands_bytes_written[$__rate_interval]))",
     "legendFormat": "written"
    }
   ]
  },
  {
   "title": "Commands Executing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "op" } },
   "targets": [
    {
     "expr": "sum(db_client_commands_executing)",
     "legendFormat": "executing"
    }
   ]
  },
  {
   "title": "Command Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "targets": [
    {
     "expr": "db_client_commands_duration_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "conns" } },
   "targets": [
    {
     "expr": "sum(db_client_connections_usage)",
     "legendFormat": "connections"
    },
    { "expr": "max(db_client_connections_max)", "legendFormat": "connections" }
   ]
  },
  {
   "title": "Connections Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "conn/s" } },
   "targets": [
    {
     "expr": "sum(rate(db_client_connections_create_time_count[$__rate_interval]))",
     "legendFormat": "connections"
    }
   ]
  }
 ]
}